name: Autopkgtest CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lxd-ubuntu-jammy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          git fetch --unshallow --tags
      - name: Install dependencies
        run: |
          sudo sed -i '/deb-src/s/^# //' /etc/apt/sources.list
          sudo apt update
          sudo apt install autopkgtest ubuntu-dev-tools devscripts openvswitch-switch
          sudo snap install lxd
          sudo lxd init --auto --storage-backend=dir
      # work around LP: #1878225 as fallback
      - name: Preparing autopkgtest-build-lxd
        run: |
          sudo patch /usr/bin/autopkgtest-build-lxd .github/workflows/autopkgtest.patch
          sudo autopkgtest-build-lxd ubuntu-daily:jammy
      - name: Prepare test
        run: |
          pull-lp-source netplan.io
          cp -r netplan.io-*/debian .
          rm -r debian/patches/  # clear any distro patches
          # temporary until 'ethtool' is a proper test dependency
          sed -i 's/wpasupplicant,/wpasupplicant, ethtool,/g' debian/tests/control
          dch -v $(git describe --tags) "Autopkgtest CI testing (Jammy)"
      - name: Run autopkgtest (incl. build)
        run: |
          sudo autopkgtest . -U --env=DPKG_GENSYMBOLS_CHECK_LEVEL=0 --env=DEB_BUILD_OPTIONS=nocheck -- lxd autopkgtest/ubuntu/jammy/amd64
