name: Check for memory issues

# This action will compile netplan with ASAN (address sanitizer) and run
# all the C unit tests and call the generator for every single file in the
# examples directory.
# The job will fail if a memory issue is detected by ASAN.

on:
  push:
    branches: [ main, 'stable/**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  memory-sanitizer:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install build depends
        run: |
          echo "APT::Get::Always-Include-Phased-Updates \"true\";" | sudo tee /etc/apt/apt.conf.d/90phased-updates
          sudo sed -i '/deb-src/s/^# //' /etc/apt/sources.list
          sudo apt update
          sudo apt -y install python3-rich python3-coverage python3-pytest python3-pytest-cov curl meson gcovr expect libcmocka-dev
          sudo apt -y build-dep netplan.io

      - name: Run unit tests
        run: |
          unbuffer ./tools/run_asan.sh

